### ISSUE TITLE
No multiple instance possible

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_dwd_pollenflug#8]
Dear @mampfes,

after installing one instance from your integration, it is not possible to install a second instance.

If i click on (Integration hinzufügen) and search to "DWD Pollenflug" i get no result

<img width="822" alt="image" src="https://user-images.githubusercontent.com/97361636/164945987-ef9daab0-334b-4903-a852-1b30bfd0d3b8.png">

You can see the first instance in the screenshot.

**Comment by mampfes** [comment]
Sorry, I can't reenact your issue. I can add multiple integrations and `DWD Pollenflug` still shows up in the "Integration suchen" window. Please check your Home Assistant configuration because this has probably nothing to do with the `DWD Pollenflug` integration.
![image](https://user-images.githubusercontent.com/375950/164968951-76c44da6-5095-41b9-8131-306e7e93a001.png)

**Comment by GerdRuetten** [comment]
After a few restarts from HA and clearing the Browser Cache it works!

Thank you for your Support!
